### ISSUE TITLE
@conda-forge-admin, please rerender

### ISSUE THREAD

**Issue by cbrueffer** [conda-forge/r-pander-feedstock#1]
@conda-forge-admin, please rerender

**Comment by cbrueffer** [comment]
Misread the conda-forge guide; disregard.

**Comment by jdblischak** [comment]
@cbrueffer I have a [script](https://github.com/jdblischak/jdb-conda/blob/master/scripts/rerender-r-packages.R) that automates this process. It finds packages that are missing builds, determines if all of their dependencies are available, rerenders them, and then sends a PR. For example, for this repo you could have run:

```
Rscript rerender-r-packages.R --force r-pander
```

The `--force` flag is necessary here because by default the script only submits a PR if the rerendering adds a new version of R to build.

If you're interested, please give it a look. And of course I'm happy to help you get setup.

**Comment by cbrueffer** [comment]
Cool, thanks for the hint! Looks very useful, I'll give it a try next time.
